services:
  bidibip_v4:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    restart: always
    volumes:
      - ./saved:/saved
    environment:
      BIDIBIP_CONFIG: "/saved/config.json"